name: Testing for pull_request to the main branch

on:
  pull_request:
    branches:
      - main

env:
  CI_SERVER: true

jobs:
  build_main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run:  make
    - name: execute
      run:  ./build/bin/main_1 succeed
