name: Testing for pull_request_to a working branch

on:
  pull_request:
    branches:
      - 'Iss[0-9]+-*'

env:
  CI_SERVER: true

jobs:
  build_working:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run:  make
    - name: run_test
      run:  ./build/bin/main_1 succeed output_matrix_file_accurate
