name: Testing for pull_request to a release branch

on:
  pull_request:
    branches:
      - 'release/**'

env:
  CI_SERVER: true

jobs:
  build_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' #install the python needed
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build
      run:  make
    - name: run_test
      run:  ./build/bin/main_1 succeed output_matrix_file_accurate good_timing
    - name: show_matrix
      run:  cat matrix.txt
    - name: check_matrix
      run:  python check_matrix.py
    - name: check_timing
      run:  python check_timing.py 100

