name: Testing for push to generate-output-file ad hoc branch

on:
  push:
    branches:
      - generate-output-file

env:
  CI_SERVER: true

jobs:
  build_working:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6 #install the python needed
    - name: build
      run:  make
    - name: run_test
      run:  ./build/bin/main_1 succeed output_matrix_file_accurate
    - name: show_matrix
      run:  cat matrix.txt
    - name: check_matrix
      run:  python check_matrix.py 

