name: Testing for push or pull_request_to a working branch

on:
  push:
    branches:
      - 'Iss[0-9]+-*'
  pull_request:
    branches:
      - 'Iss[0-9]+-*'

env:
  CI_SERVER: true

jobs:
  build_working:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run:  make
    - name: execute
      # run: ./build/bin/main_1 succeed
      run: ./build/bin/main_1 fail

